version: '3'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
  
  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
